---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios' or
      ansible_network_os == 'junos'

- name: NXOS configure hostname 
  nxos_config:
    lines: hostname {{ hostname_string | default( {{ inventory_hostname }} ) }}  
  when: >
    ansible_network_os == 'nxos'
  tags: 
    - hostname_config